name: Generate image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/*.yaml
      - "**/*.go"
      - Dockerfile

jobs:
  build:
    name: Building a new docker image
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: vitruveo.protocol.geth
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest -f Dockerfile --network host .
          docker push $REGISTRY/$REPOSITORY:latest
